INSERT INTO PUBLIC.CREDENTIALS (ID, PASSWORD, ROLE, USERNAME) VALUES (1, '12345678', 1, 'Obama');

INSERT INTO PUBLIC.USERS (ID, FIRST_NAME, LAST_NAME, SCORE, CREDENTIALS_ID) VALUES (1, 'Barak', 'Obama', 0, 1);